name: MagiaBorras
main: es.cristichi.magiaborras.main.MagiaPlugin
depend: []
version: 1.7.002
api-version: 1.13
commands:
  magia:
    description: Controla el plugin.
    aliases: [cm, cristichimagia, magiaborras]
    usage: /magia help
permissions:
  magiaborras.*:
    children:
      magiaborras.use: true
      magiaborras.create: true
      magiaborras.admin: true
  magiaborras.use:
    default: op
  magiaborras.create:
    default: op
  magiaborras.admin:
    default: op