name: MagiaBorras
main: main.MagiaPlugin
version: 0.4
api-version: 1.13
depend: [Citizens]
commands:
  magia:
    description: Controla el plugin.
    aliases: [cm, cristichimagia]
    usage: /magia help
permissions:
  magiaborras.*:
    children:
      magiaborras.use: true
      magiaborras.create: true
      magiaborras.admin: true
  magiaborras.use:
    default: op
  magiaborras.create:
    default: op
  magiaborras.admin:
    default: op