name: MagiaBorras
main: es.cristichi.magiaborras.main.MagiaPlugin
depend: []
version: 1.9.0
api-version: 1.13
commands:
  magia:
    description: Controla el plugin.
    aliases: [cm, cristichimagia, magiaborras]
    usage: /magia help
permissions:
  magiaborras.*:
    children:
      magiaborras.use: true
      magiaborras.craft: true
      magiaborras.admin: true
  magiaborras.use:
    default: true
  magiaborras.craft:
    default: true
  magiaborras.admin:
    default: op